CREATE DATABASE ONLINETUTOR;

USE ONLINETUTOR;

CREATE TABLE REGISTERED_USERS (
	ID INT SIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MATRIC_NO VARCHAR (40) NOT NULL,
	LASTNAME  VARCHAR (40) NOT NULL,
	FIRSTNAME VARCHAR (40) NOT NULL,
	GENDER VARCHAR (8) NOT NULL,
	BIRTHDAY DATE NOT NULL,
	TITLE VARCHAR (15) NOT NULL,
	INSTITUTION VARCHAR (100) NOT NULL,
	FACULTY VARCHAR (40) NOT NULL,
	DEPARTMENT VARCHAR (40) NOT NULL,
	DISCIPLINE VARCHAR (40) NOT NULL,
	PICTURE VARCHAR (100),
	AGREEMENT_STATUS VARCHAR (5) NOT NULL,
	EMAIL VARCHAR (40) NOT NULL,
	PHONE VARCHAR (20) NOT NULL,
	USERNAME VARCHAR (20) NOT NULL UNIQUE,
	PASSWORD VARCHAR (40) NOT NULL,
	SECURITY_QUESTION VARCHAR (50) NOT NULL,
	SECURITY_ANSWER VARCHAR (50) NOT NULL,
	USER_TYPE ENUM('lecturer', 'student') NOT NULL
);

CREATE TABLE FEEDBACK (
	ID INT SIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	SENDER INT NOT NULL,
	SENDER_TYPE ENUM('lecturer', 'student') NOT NULL,
	FEEDBACK_MESSAGE TEXT NOT NULL,
	POST_DATE DATETIME NOT NULL
);

CREATE TABLE FRIENDS (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	FRIEND_ID INT NOT NULL,
	REQUESTOR_ID INT NOT NULL,
	CONFIRM ENUM('YES', 'NO'), 
	USER_TYPE VARCHAR(10)
);

CREATE TABLE CHAT (
	POST_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	SENDER INT NOT NULL, 
	RECEIVER INT NOT NULL, 
	POST TEXT NOT NULL, 
	MEDIA_URL VARCHAR(120), 
	POST_DATE DATETIME NOT NULL
);

CREATE TABLE STUDENTS (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	LEC_ID INT NOT NULL,
	STUDENT_ID INT NOT NULL, 
	CONFIRM ENUM('YES', 'NO')
);

CREATE TABLE COURSES(
	COURSE_ID TINYINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	LEC_ID INT NOT NULL,
	COURSE_CODE VARCHAR(15) NOT NULL, 
	COURSE_TITLE VARCHAR(100) NOT NULL, 
	COURSE_DESCRIPTION TEXT, 
	UNIT TINYINT NOT NULL
);

CREATE TABLE REGISTERED_COURSES (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	LEC_ID INT NOT NULL, 
	STUDENT_ID INT NOT NULL,  
	COURSE_ID TINYINT NOT NULL, 
	COURSE_STATUS VARCHAR (15) NOT NULL
);

CREATE TABLE TEST (
	ID TINYINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	LEC_ID INT NOT NULL,
	TEST_ID TINYINT, 
	COURSE_ID TINYINT NOT NULL, 
	DURATION TIME NOT NULL, 
	DEADLINE DATETIME,  
	MARK TINYINT NOT NULL, 
	NO_OF_QUESTIONS TINYINT NOT NULL, 
	TEST_TYPE ENUM('TEST', 'EXAM') NOT NULL, 
	TEST_STATUS ENUM('OPENED', 'CLOSED') NOT NULL
);

CREATE TABLE QUESTIONS (
	QUESTION_ID TINYINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	LEC_ID INT NOT NULL,
	COURSE_ID TINYINT NOT NULL, 
	TEST_ID TINYINT NOT NULL, 
	QUESTIONS TEXT NOT NULL, 
	OPTION_A VARCHAR (100), 
	OPTION_B VARCHAR (100), 
	OPTION_C VARCHAR (100), 
	OPTION_D VARCHAR (100), 
	CORRECT_OPTION ENUM('A', 'B', 'C', 'D') 
);

CREATE TABLE SCORE_BOARD (
	SCORE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	LEC_ID INT NOT NULL,
	STUDENT_ID INT NOT NULL, 
	COURSE_ID TINYINT NOT NULL,  
	TEST_ID TINYINT, 
	DISCUSSION_ID TINYINT, 
	SCORE TINYINT NOT NULL, 
	SCORE_TYPE ENUM('TEST', 'EXAM', 'DISCUSSION') NOT NULL
);

CREATE TABLE DISCUSSION ( 
	DISCUSSION_ID TINYINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	LEC_ID INT NOT NULL, 
	COURSE_ID TINYINT NOT NULL, 
	DISCUSSION_TOPIC TEXT NOT NULL, 
	POST_DATE DATETIME NOT NULL, 
	TYPE ENUM('OPEN', 'CLOSE') NOT NULL 
);

CREATE TABLE POST ( 
	POST_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	LEC_ID INT NOT NULL,
	STUDENT_ID INT NOT NULL, 
	DISCUSSION_ID TINYINT NOT NULL, 
	COURSE_ID TINYINT NOT NULL, 
	POST_DATE DATETIME NOT NULL, 
	POST_TEXT TEXT NOT NULL, 
	TYPE ENUM('OPEN', 'CLOSE') NOT NULL, 
	GRADED ENUM('YES', 'NO') NOT NULL 
);

CREATE TABLE ANNOUNCEMENT( 
	LEC_ID INT NOT NULL PRIMARY KEY,
	POST_MESSAGE TEXT NOT NULL, 
	POST_DATE DATETIME NOT NULL
);

CREATE TABLE NOTE  (
	USER_ID INT NOT NULL PRIMARY KEY, 
	COURSE_ID TINYINT NOT NULL, 
	TITLE VARCHAR (100), 
	NOTE TEXT NOT NULL, 
	NOTE_DATE DATETIME NOT NULL
);

CREATE TABLE VIDEOS (
  LEC_ID INT NOT NULL PRIMARY KEY, 
  COURSE_ID TINYINT NOT NULL, 
  VIDEO_URL VARCHAR (150) NOT NULL, 
  VIDEO_NAME VARCHAR  (100) NOT NULL, 
  VIDEO_CAPTION VARCHAR (100) NOT NULL
);